// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wiki/v1/wiki.proto

package wikiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WikiEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Bot           bool                   `protobuf:"varint,2,opt,name=bot,proto3" json:"bot,omitempty"`
	ServerUrl     string                 `protobuf:"bytes,3,opt,name=server_url,json=serverUrl,proto3" json:"server_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WikiEvent) Reset() {
	*x = WikiEvent{}
	mi := &file_wiki_v1_wiki_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WikiEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WikiEvent) ProtoMessage() {}

func (x *WikiEvent) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_v1_wiki_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WikiEvent.ProtoReflect.Descriptor instead.
func (*WikiEvent) Descriptor() ([]byte, []int) {
	return file_wiki_v1_wiki_proto_rawDescGZIP(), []int{0}
}

func (x *WikiEvent) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *WikiEvent) GetBot() bool {
	if x != nil {
		return x.Bot
	}
	return false
}

func (x *WikiEvent) GetServerUrl() string {
	if x != nil {
		return x.ServerUrl
	}
	return ""
}

var File_wiki_v1_wiki_proto protoreflect.FileDescriptor

const file_wiki_v1_wiki_proto_rawDesc = "" +
	"\n" +
	"\x12wiki/v1/wiki.proto\x12\awiki.v1\"P\n" +
	"\tWikiEvent\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x10\n" +
	"\x03bot\x18\x02 \x01(\bR\x03bot\x12\x1d\n" +
	"\n" +
	"server_url\x18\x03 \x01(\tR\tserverUrlB+Z)ch7-observability/internal/wiki/v1;wikiv1b\x06proto3"

var (
	file_wiki_v1_wiki_proto_rawDescOnce sync.Once
	file_wiki_v1_wiki_proto_rawDescData []byte
)

func file_wiki_v1_wiki_proto_rawDescGZIP() []byte {
	file_wiki_v1_wiki_proto_rawDescOnce.Do(func() {
		file_wiki_v1_wiki_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wiki_v1_wiki_proto_rawDesc), len(file_wiki_v1_wiki_proto_rawDesc)))
	})
	return file_wiki_v1_wiki_proto_rawDescData
}

var file_wiki_v1_wiki_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wiki_v1_wiki_proto_goTypes = []any{
	(*WikiEvent)(nil), // 0: wiki.v1.WikiEvent
}
var file_wiki_v1_wiki_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wiki_v1_wiki_proto_init() }
func file_wiki_v1_wiki_proto_init() {
	if File_wiki_v1_wiki_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wiki_v1_wiki_proto_rawDesc), len(file_wiki_v1_wiki_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wiki_v1_wiki_proto_goTypes,
		DependencyIndexes: file_wiki_v1_wiki_proto_depIdxs,
		MessageInfos:      file_wiki_v1_wiki_proto_msgTypes,
	}.Build()
	File_wiki_v1_wiki_proto = out.File
	file_wiki_v1_wiki_proto_goTypes = nil
	file_wiki_v1_wiki_proto_depIdxs = nil
}
